import { ThemeProvider, createTheme } from "@mui/material";
import type { AppProps } from "next/app";
import Head from "next/head";
import GlobalStyle from "theme/GlobalStyle";
import { Header } from "../packages/Header";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      {/* <ThemeProvider theme={theme}> */}
      <Header />
      <Component {...pageProps} />
      {/* </ThemeProvider> */}
    </>
  );
}

export default MyApp;
